### ISSUE TITLE
net_teacher.module.infer_encoder_teacher_mode and net_teacher.module.infer_decoder_teacher_mode

### ISSUE THREAD

**Issue by tricky61** [choiHkk/nix-tts#1]
the demo sounds good
but was these two functions missed? I cannot find them

**Comment by choiHkk** [comment]
you can find the functions from jupyter notebook.

**Comment by Wolfman1219** [comment]
I can't find them. Can anybody help me?

**Comment by Wolfman1219** [comment]
Where initialized these functions?
